spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            endpoint: ${AZURE_KEY_VAULT_ENDPOINT} # environment variable
  datasource:
    url: ${datasource.url} # secrets from azure key vault
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    hibernate:
      ddl-auto: none # we explicitly turn of the DDL (data definition language) auto-generation
    show-sql: false
