spring:
  profiles:
    active: dev #default mode. During production, this will be replaced to "prod" due to Azure environment variable
  web:
    resources:
      add-mappings: false
api:
  endpoint:
    base-url: /api/v1
server:
  port: 80